import pandas as pd
from pathlib import Path

# Load the station-level dataset generated by your previous script
# We use the station-level aggregation logic to see the final features
IN_DATA = Path("outputs/train_delay_risk_dataset_2024.csv")

def identify_outlier(cluster_id=4):
    if not IN_DATA.exists():
        print(f"Error: {IN_DATA} not found. Run cluster_delay_driver_viz.py first.")
        return

    df = pd.read_csv(IN_DATA)

    # Re-run the aggregation to get the same station-level view as the cluster script
    station_stats = df.groupby("station").agg(
        delay_mean=("delay_risk", "mean"),
        traffic=("total_stops", "mean"),
        lat=("lat", "first"),
        lon=("lon", "first"),
        t2m_mean=("t2m_c", "mean"),
        wind_mean=("wind_ms", "mean")
    ).reset_index()

    # Note: We need to map the cluster IDs back. 
    # Since the cluster labels are not saved in the CSV yet, 
    # we use the logic from your driver script to re-identify the cluster.
    # Alternatively, if you saved 'cluster' to the CSV, we just filter.
    
    # Let's check if 'cluster' exists in your current output CSV
    if "cluster" in df.columns:
        # Get the station(s) in the specified cluster
        outlier_stations = df[df["cluster"] == cluster_id]["station"].unique()
        
        print(f"--- Cluster {cluster_id} Outlier Analysis ---")
        for name in outlier_stations:
            stats = station_stats[station_stats["station"] == name].iloc[0]
            print(f"\nSTATION NAME: {name}")
            print("-" * 30)
            print(f"Avg Delay Risk: {stats['delay_mean']:.2%}")
            print(f"Traffic Volume (Avg Monthly Stops): {stats['traffic']:.1f}")
            print(f"Coordinates: {stats['lat']}, {stats['lon']}")
            print(f"Avg Temperature: {stats['t2m_mean']:.2f}°C")
            print(f"Avg Wind Speed: {stats['wind_mean']:.2f} m/s")
    else:
        print("Column 'cluster' not found in CSV. Please ensure cluster_delay_driver_viz.py saves the cluster column.")

if __name__ == "__main__":
    identify_outlier(4)